name: Node.js Client With React.js
'on':
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build React Project
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build --if-present
      - name: List output files
        run: ls
  deploy:
    needs:
      - build
    name: Deploy to ftp server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: '${{ secrets.FTP_SERVER }}/drift/'
          ftp-username: '${{ secrets.FTP_USERNAME }}'
          ftp-password: '${{ secrets.FTP_PASSWORD }}'
          local-dir: build
